#!/bin/bash


if test "$1" = "config"
then
  echo "graph_title Nginx requests"
  echo "graph_args --base 1000"
  echo "graph_category nginx"
  echo "graph_vlabel Request per second"
  echo "request.label req/sec"
  echo "request.type DERIVE"
  echo "request.min 0"
  echo "request.label requests port 80"
  echo "request.draw LINE2"
  exit
fi


URL=http://localhost/nginx_status

#Recuperamos
DATA=$(curl -s ${URL} | head -3 | tail -1 | awk '{print $NF}')


#Devolvemos
echo "request.value ${DATA}"