#!/bin/bash
# -*- sh -*-
#
# Plugin to monitor the number of PHP5-FPM processes on the machine.
#
# Copyright TJ Stein 2010 http://constantshift.com
#
# Parameters:
#
# config (required)
# autoconf (optional - used by munin-config)
#
# Magick markers (optional - used by munin-config and som installation
# scripts):
#%# family=manual
#%# capabilities=autoconf

PHP_BIN="php-fpm"
PHP_POOL="www"

if [ "$1" = "autoconf" ]; then
echo yes
exit 0
fi

if [ "$1" = "config" ]; then
echo 'graph_title PHP5-FPM Accepted Connections'
echo 'graph_args --base 1024 -l 0'
echo 'graph_vlabel Connections'
echo 'graph_category PHP'
echo 'graph_info Plugin created by TJ Stein'
echo 'accepted.label Accepted'
echo 'accepted.draw AREA'
echo 'accepted.type DERIVE'
echo 'accepted.min 0'
exit 0
fi


export SCRIPT_FILENAME="/status"
export SCRIPT_NAME="/status"
export REQUEST_METHOD="GET"

DATA=$(/usr/bin/cgi-fcgi -bind -connect /var/run/php5-fpm.sock )

echo "${DATA}" | grep "accepted conn" | awk '{print "accepted.value " $NF}'


exit
